name: Bump Version Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"  # Avoid version bumps triggering themselves
    runs-on: ubuntu-20.04

    permissions:
      contents: write  # This gives write access to push changes back to the repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Ensures we use GITHUB_TOKEN, not the default GitHub credentials

      - name: Set up Python environment
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir bump2version

      - name: Get current version
        id: get_version
        run: |
          current_version=$(grep -oP '(?<=# version )\d+\.\d+\.\d+' version.md)
          echo "current_version=${current_version}" >> $GITHUB_ENV

      - name: Bump version
        run: |
          bump2version patch --current-version ${{ env.current_version }} version.md --allow-dirty

      - name: Push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add version.md
          git commit -m "Bump version to ${{ env.current_version }}"
          git push origin main --follow-tags