name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pytest pytest-cov  # Installation de pytest-cov pour la couverture
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)/src
          pytest --cov=src --cov-report=xml tests/  # Génère un rapport XML de couverture des tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3 
        with:
          file: ./coverage.xml
          fail_ci_if_error: true