name: Release Management

on:
  workflow_dispatch:
    inputs:
      typeOfRelease:
        description: 'Type of Release (major, minor, patch, custom)'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch
        - custom
      version:
        description: 'Version of the release (only for custom release)'
        required: false
        type: string
      releaseNotes:
        description: 'Release notes'
        required: true
        type: string
      generateReleaseNotes:
        description: 'Auto generate release notes'
        required: false
        default: true
        type: boolean
      releaseDraft:
        description: 'Release draft'
        required: false
        default: false
        type: boolean
      preRelease:
        description: 'Pre-release'
        required: false
        default: false
        type: boolean
      targetCommitish:
        description: 'Target commitish'
        required: false
        default: 'main'
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Release Management
      uses: Consuma/release-management@v1
      with:
        typeOfRelease: ${{ github.event.inputs.typeOfRelease }}
        version: ${{ github.event.inputs.version }}
        releaseNotes: ${{ github.event.inputs.releaseNotes }}
        generateReleaseNotes: ${{ github.event.inputs.generateReleaseNotes }}
        releaseDraft: ${{ github.event.inputs.releaseDraft }}
        preRelease: ${{ github.event.inputs.preRelease }}
        targetCommitish: ${{ github.event.inputs.targetCommitish }}
        githubToken: ${{ secrets.GITHUB_TOKEN }